export const MODELS_LIST_REQUEST = "MODELS.LIST_REQUEST";
export const MODELS_LIST_SUCCESS = "MODELS.LIST_SUCCESS";
export const MODELS_LIST_FAIL = "MODELS.LIST_FAIL";

export const MODELS_DETAILS_REQUEST = "MODELS.DETAILS_REQUEST";
export const MODELS_DETAILS_SUCCESS = "MODELS.DETAILS_SUCCESS";
export const MODELS_DETAILS_FAIL = "MODELS.DETAILS_FAIL";
